export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
// export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const SET_THONG_TIN_NGUOI_DUNG_UPDATE = "SET_THONG_TIN_NGUOI_DUNG_UPDATE";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_FORM_EDIT_USER = "OPEN_FORM_EDIT_USER";
export const SET_SUBMIT_EDIT_USER = "SET_SUBMIT_EDIT_USER";
export const EDIT_USER = 'EDIT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_CLIENT = 'UPDATE_USER_CLIENT';
